/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html", "./js/**/*.js"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#313030",
        "secondary-container": "#e4e2e1",
        "tertiary": "#485e8b",
        "on-error": "#ffffff",
        "primary-container": "#c5a059",
        "surface-container-low": "#f6f3f2",
        "on-secondary-fixed": "#1b1c1c",
        "on-secondary-container": "#656464",
        "secondary": "#5f5e5e",
        "on-primary-container": "#4e3700",
        "on-surface-variant": "#4e4639",
        "on-tertiary": "#ffffff",
        "surface-bright": "#fcf9f8",
        "surface-tint": "#775a19",
        "secondary-fixed-dim": "#c8c6c5",
        "on-tertiary-container": "#233a65",
        "tertiary-fixed": "#d8e2ff",
        "on-surface": "#1c1b1b",
        "on-background": "#1c1b1b",
        "on-tertiary-fixed-variant": "#304671",
        "secondary-fixed": "#e4e2e1",
        "surface-container-highest": "#e5e2e1",
        "surface-variant": "#e5e2e1",
        "outline": "#7f7667",
        "on-primary-fixed-variant": "#5d4201",
        "on-tertiary-fixed": "#001a41",
        "primary": "#775a19",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#261900",
        "surface-dim": "#dcd9d9",
        "surface-container": "#f0eded",
        "surface": "#fcf9f8",
        "outline-variant": "#d1c5b4",
        "error-container": "#ffdad6",
        "background": "#fcf9f8",
        "inverse-primary": "#e9c176",
        "tertiary-container": "#8fa5d6",
        "tertiary-fixed-dim": "#b0c6f9",
        "inverse-on-surface": "#f3f0ef",
        "error": "#ba1a1a",
        "primary-fixed": "#ffdea5",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#e9c176",
        "on-secondary-fixed-variant": "#474747",
        "surface-container-high": "#eae7e7"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
